DROP TABLE IF EXISTS books;
CREATE TABLE books (
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
creation_date DATETIME  DEFAULT CURRENT_TIMESTAMP,
genre ENUM('ADVENTURE','DETECTIVE','DRAMA','FANTASY','HORROR','OTHER'),
name VARCHAR(255),
price DECIMAL(19,2));

DROP TRIGGER IF EXISTS set_now_date;
DELIMITER $$
CREATE TRIGGER set_now_date
BEFORE INSERT ON books
FOR EACH ROW
BEGIN
IF NEW.creation_date IS NULL THEN
SET NEW.creation_date=CURRENT_TIMESTAMP;
END IF;
END $$
DELIMITER ;