CREATE TABLE books (
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
creation_date DATETIME  DEFAULT CURRENT_TIMESTAMP,
genre ENUM('ADVENTURE','DETECTIVE','DRAMA','FANTASY','HORROR','OTHER'),
name VARCHAR(255),
price DECIMAL(19,2));